name: CI Workflow

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0 # Or any other desired MySQL version
        env:
          MYSQL_ROOT_PASSWORD: password # Use GitHub Secrets for sensitive data
          MYSQL_DATABASE: ticketmasterDB
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 172.18.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile
        run: mvn --batch-mode compile

      - name: Spotless Check
        run: mvn --batch-mode spotless:check

      - name: Build (package)
        run: mvn --batch-mode package

      - name: Test
        run: mvn --batch-mode test
        env:
          DB_HOST: 172.18.0.1 # Connect to the service's internal IP or localhost as seen from the job
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: ticketmasterDB